### ISSUE TITLE
combineLatest pushEach strategy

### ISSUE THREAD

**Issue by oliviermilla** [ReactiveBayes/Rocket.jl#55] opened 2024-07-12 11:24 UTC
Hello,

`combineLatest` offers both `pushEach()` and `pushNew()` strategies.

From the documentation, one would expect the first to publish at the first update of any of its sources and the latter to publish only after all sources have emitted at least once.

But

```julia
using Rocket
a = combineLatest(never() |> async(0), from([1,2]) |> async(0))
subscribe!(a, logger())
```

yields

```
julia> [LogActor] Completed
julia> 
```

While I expected to get `(nothing, 1), (nothing, 2)` before completion.

Am I reading the documentation right? 
Would another operator yield as soon as ANY source yields?

Thank you ❤️

**Comment by bvdmitri** [comment] 2024-07-13 08:47
`combineLatest` combines values from both sources into a single event, but you’re probably looking for [`merged`](https://reactivebayes.github.io/Rocket.jl/stable/observables/types/merged/), which merges different streams of events into a single stream. `combineLatest` cannot emit a value if one of the sources does not emit anything (as in your example with `never`).

**Closed by bvdmitri** 2024-07-13 08:47 UTC

**Comment by bvdmitri** [comment] 2024-07-13 08:50
Also [here](https://reactivebayes.github.io/Rocket.jl/stable/observables/types/combined/#Rocket.combineLatest)

> To ensure that the output tuple has a consistent length, combineLatest waits for all input Observables to emit at least once before it starts emitting results. This means that if some Observable emits values before other Observables started emitting, all these values but the last will be lost. On the other hand, if some Observable does not emit a value but completes, the resulting Observable will complete simultaneously without emitting anything.

**Comment by bvdmitri** [comment] 2024-07-13 09:20
For example 
```julia
julia> subscribe!(combineLatest(of(nothing), from([ 1, 2 ])), logger())
[LogActor] Data: (nothing, 1)
[LogActor] Data: (nothing, 2)
[LogActor] Completed
```

**Comment by oliviermilla** [comment] 2024-07-13 10:56
Hello @bvdmitri,

Thank you for taking the time. I am, in fact, looking for `combineLatest`; I simply want a tuple of all inputs, whether or not they have emitted something yet. 

`merged` serialize events but I could use it to trigger a single time, hopefully first.

Something like

```Julia
subscribe!(combineLatest(merged(of(nothing),source1), merged(of(nothing), source2)), logger())
```

I'll look into it but it looks like I have to generate fake signals to get combineLatest, while pushEach() describes a trigger as soon as ANY input emits, which is exactly what I'm looking for! :)

Have a great weekend.

**Comment by bvdmitri** [comment] 2024-07-13 11:55
The problem is that `never` _never_ completes, so `combineLatest` just waits indefinitely, you can use `default_if_empty` operator, but this one also requires for the internal stream to _complete_, e.g:

```julia
julia> a = combineLatest(completed() |> default_if_empty(nothing) |> async(0), from([1,2]) |> async(0))
CombineLatestObservable(Tuple{Any, Int64})

julia> subscribe!(a, logger())
[LogActor] Data: (nothing, 1)
[LogActor] Data: (nothing, 2)
CombineLatestSubscription()
```

**Comment by bauglir** [comment] 2024-07-13 13:01
Perhaps using [`start_with`](https://reactivebayes.github.io/Rocket.jl/stable/operators/transformation/start_with/#Rocket.start_with) is an alternative to ensure at least one known value to emit for each input (which could then be ignored if necessary)?

**Comment by oliviermilla** [comment] 2024-07-13 15:27
start_with seems to be the best option here.

Thanks!
